routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UnltwebController;

Route::get('', function () {
    return view('inicio');
});

Route::get('/loguear', function () {
    return view('auth.login');
});

Auth::routes();

Route::resource('unltwebs', UnltwebController::class)->middleware('auth'); 


#region HUEVO de PASCUA
    Route::get('/hola', function () {
        return "Hola Caranlito: Huevo de pascua
        <br>
        <h3>GOLEM - Jorge Luis bordes </h1>
    <br>Si (como afirma el griego en el Cratilo)
    <br>el nombre es arquetipo de la cosa
    <br>en las letras de 'rosa' está la rosa
    <br>y todo el Nilo en la palabra 'Nilo'.
    <br>
    <br>Y, hecho de consonantes y vocales,
    <br>habrá un terrible Nombre, que la esencia
    <br>cifre de Dios y que la Omnipotencia
    <br>guarde en letras y sílabas cabales.
    <br>
    <br>Adán y las estrellas lo supieron
    <br>en el Jardín. La herrumbre del pecado
    <br>(dicen los cabalistas) lo ha borrado
    <br>y las generaciones lo perdieron.
    <br>
    <br>Los artificios y el candor del hombre
    <br>no tienen fin. Sabemos que hubo un día
    <br>en que el pueblo de Dios buscaba el Nombre
    <br>en las vigilias de la judería.
    <br>
    <br>No a la manera de otras que una vaga
    <br>sombra insinúan en la vaga historia,
    <br>aún está verde y viva la memoria
    <br>de Judá León, que era rabino en Praga.
    <br>
    <br>Sediento de saber lo que Dios sabe,
    <br>Judá León se dio a permutaciones
    <br>de letras y a complejas variaciones
    <br>y al fin pronunció el Nombre que es la Clave,
    <br>
    <br>la Puerta, el Eco, el Huésped y el Palacio,
    <br>sobre un muñeco que con torpes manos
    <br>labró, para enseñarle los arcanos
    <br>de las Letras, del Tiempo y del Espacio.
    <br>
    <br>El simulacro alzó los soñolientos
    <br>párpados y vio formas y colores
    <br>que no entendió, perdidos en rumores
    <br>y ensayó temerosos movimientos.
    <br>
    <br>Gradualmente se vio (como nosotros)
    <br>aprisionado en esta red sonora
    <br>de Antes, Después, Ayer, Mientras, Ahora,
    <br>Derecha, Izquierda, Yo, Tú, Aquellos, Otros.
    <br>
    <br>(El cabalista que ofició de numen
    <br>a la vasta criatura apodó Golem;
    <br>estas verdades las refiere Scholem
    <br>en un docto lugar de su volumen.)
    <br>
    <br>El rabí le explicaba el universo
    <br>'esto es mi pie; esto el tuyo, esto la soga.'
    <br>y logró, al cabo de años, que el perverso
    <br>barriera bien o mal la sinagoga.
    <br>
    <br>Tal vez hubo un error en la grafía
    <br>o en la articulación del Sacro Nombre;
    <br>a pesar de tan alta hechicería,
    <br>no aprendió a hablar el aprendiz de hombre.
    <br>
    <br>Sus ojos, menos de hombre que de perro
    <br>y harto menos de perro que de cosa,
    <br>seguían al rabí por la dudosa
    <br>penumbra de las piezas del encierro.
    <br>
    <br>Algo anormal y tosco hubo en el Golem,
    <br>ya que a su paso el gato del rabino
    <br>se escondía. (Ese gato no está en Scholem
    <br>pero, a través del tiempo, lo adivino.)
    <br>
    <br>Elevando a su Dios manos filiales,
    <br>las devociones de su Dios copiaba
    <br>o, estúpido y sonriente, se ahuecaba
    <br>en cóncavas zalemas orientales.
    <br>
    <br>El rabí lo miraba con ternura
    <br>y con algún horror. '¿Cómo' (se dijo)
    <br>'pude engendrar este penoso hijo
    <br>y la inacción dejé, que es la cordura?'
    <br>
    <br>'¿Por qué di en agregar a la infinita
    <br>serie un símbolo más? ¿Por qué a la vana
    <br>madeja que en lo eterno se devana,
    <br>di otra causa, otro efecto y otra cuita?'
    <br>
    <br>En la hora de angustia y de luz vaga,
    <br>en su Golem los ojos detenía.
    <br>¿Quién nos dirá las cosas que sentía
    <br>Dios, al mirar a su rabino en Praga?
    <br>
    ";
    });
#endregion

app/Models/Unltweb.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Unltweb
 *
 * @property $id
 * @property $apellido
 * @property $nombre
 * @property $correo
 * @property $entorno
 * @property $orientacion
 * @property $conocimientos
 * @property $tp1_html
 * @property $tp2_css
 * @property $tp3_servidores
 * @property $tp4_http
 * @property $encuentro
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Unltweb extends Model
{
  protected $table ='unltwebs';
    
    static $rules = [
		'apellido' => 'required',
		'nombre' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['apellido','nombre','correo','entorno','orientacion','conocimientos','tp1_html','tp2_css','tp3_servidores','tp4_http','encuentro'];



}

app/Http/Controllers/UnltwebController.php
<?php

namespace App\Http\Controllers;

use App\Models\Unltweb;
use Illuminate\Http\Request;

/**
 * Class UnltwebController
 * @package App\Http\Controllers
 */
class UnltwebController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $unltwebs = Unltweb::paginate();

        return view('unltweb.index', compact('unltwebs'))
            ->with('i', (request()->input('page', 1) - 1) * $unltwebs->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $unltweb = new Unltweb();
        return view('unltweb.create', compact('unltweb'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Unltweb::$rules);

        $unltweb = Unltweb::create($request->all());

        return redirect()->route('unltwebs.index')
            ->with('success', '¡Alumno creado!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $unltweb = Unltweb::find($id);

        return view('unltweb.show', compact('unltweb'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $unltweb = Unltweb::find($id);

        return view('unltweb.edit', compact('unltweb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Unltweb $unltweb
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Unltweb $unltweb)
    {
        request()->validate(Unltweb::$rules);

        $unltweb->update($request->all());

        return redirect()->route('unltwebs.index')
            ->with('success', '¡Datos del alumno actualizados!');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $unltweb = Unltweb::find($id)->delete();

        return redirect()->route('unltwebs.index')
            ->with('success', 'Alumno borrado de la base.');
    }
}

resources/views/unltweb/create.blade.php
@extends('layouts.admin_raiz')

@section('contenido_app')

@include('layouts.barraSuperiorAdmin')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Alta Alummno</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('unltwebs.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('unltweb.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/unltweb/edit.blade.php
@extends('layouts.admin_raiz')

@section('contenido_app')

@include('layouts.barraSuperiorAdmin')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Actualizar datos:</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('unltwebs.update', $unltweb->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('unltweb.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/unltweb/form.blade.php
<div class="box box-info padding-1 alert-success p-5 m-3 container">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('apellido') }}
            {{ Form::text('apellido', $unltweb->apellido, ['class' => 'form-control' . ($errors->has('apellido') ? ' is-invalid' : ''), 'placeholder' => 'Apellido']) }}
            {!! $errors->first('apellido', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $unltweb->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('correo') }}
            {{ Form::text('correo', $unltweb->correo, ['class' => 'form-control' . ($errors->has('correo') ? ' is-invalid' : ''), 'placeholder' => 'Correo']) }}
            {!! $errors->first('correo', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('entorno') }}
            {{ Form::text('entorno', $unltweb->entorno, ['class' => 'form-control' . ($errors->has('entorno') ? ' is-invalid' : ''), 'placeholder' => 'Entorno']) }}
            {!! $errors->first('entorno', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('orientacion') }}
            {{ Form::text('orientacion', $unltweb->orientacion, ['class' => 'form-control' . ($errors->has('orientacion') ? ' is-invalid' : ''), 'placeholder' => 'Orientacion']) }}
            {!! $errors->first('orientacion', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('conocimientos') }}
            {{ Form::text('conocimientos', $unltweb->conocimientos, ['class' => 'form-control' . ($errors->has('conocimientos') ? ' is-invalid' : ''), 'placeholder' => 'Conocimientos']) }}
            {!! $errors->first('conocimientos', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('tp1_html') }}
            {{ Form::text('tp1_html', $unltweb->tp1_html, ['class' => 'form-control' . ($errors->has('tp1_html') ? ' is-invalid' : ''), 'placeholder' => 'Tp1 Html']) }}
            {!! $errors->first('tp1_html', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('tp2_css') }}
            {{ Form::text('tp2_css', $unltweb->tp2_css, ['class' => 'form-control' . ($errors->has('tp2_css') ? ' is-invalid' : ''), 'placeholder' => 'Tp2 Css']) }}
            {!! $errors->first('tp2_css', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('tp3_servidores') }}
            {{ Form::text('tp3_servidores', $unltweb->tp3_servidores, ['class' => 'form-control' . ($errors->has('tp3_servidores') ? ' is-invalid' : ''), 'placeholder' => 'Tp3 Servidores']) }}
            {!! $errors->first('tp3_servidores', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('tp4_http') }}
            {{ Form::text('tp4_http', $unltweb->tp4_http, ['class' => 'form-control' . ($errors->has('tp4_http') ? ' is-invalid' : ''), 'placeholder' => 'Tp3 Http']) }}
            {!! $errors->first('tp4_http', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('encuentro') }}
            {{ Form::text('encuentro', $unltweb->encuentro, ['class' => 'form-control' . ($errors->has('encuentro') ? ' is-invalid' : ''), 'placeholder' => 'Encuentro']) }}
            {!! $errors->first('encuentro', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary btn-block">Envía / Actualiza</button>
    </div>
</div>

resources/views/unltweb/index.blade.php
@extends('layouts.admin_raiz')

@section('contenido_app')

@include('layouts.barraSuperiorAdmin')

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                Tecnologías Web
                            </span>

                             <div class="float-right">
                                <a href="{{ route('unltwebs.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  Nuevo Alumno
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover table-bordered" id='tabla_resultados'>
                                <thead class="thead">
                                    <tr>

										<th>Apellido</th>
										<th>Nombre</th>
										{{-- <th>Correo</th> --}}
                                        <th>Tp1 Html</th>
										<th>Tp2 Css</th>
										<th>Tp3 Servidores</th>
										<th>Tp4 Http</th>
                                        <th>Encuentro</th> 
                                        <th>Acciones</th>
										{{-- <th>Entorno</th>
										<th>Orientacion</th>
										<th>Conocimientos</th>--}}
										
										

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($unltwebs as $unltweb)
                                        <tr class="text-center">
                                            {{-- <td>{{ ++$i }}</td> --}}

											<td>{{ $unltweb->apellido }}</td>
											<td>{{ $unltweb->nombre }}</td>
                                            <td>{{ $unltweb->tp1_html }}</td>
											<td>{{ $unltweb->tp2_css }}</td>
											<td>{{ $unltweb->tp3_servidores }}</td>
											<td>{{ $unltweb->tp4_http }}</td>
											{{-- <td>{{ $unltweb->correo }}</td> --}}
											{{-- <td>{{ $unltweb->entorno }}</td>
											<td>{{ $unltweb->orientacion }}</td>
											<td>{{ $unltweb->conocimientos }}</td> --}}
										
											<td>{{ $unltweb->encuentro }}</td> 

                                            <td>
                                                <form action="{{ route('unltwebs.destroy',$unltweb->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('unltwebs.show',$unltweb->id) }}"><i class="fa fa-fw fa-eye"></i> Mostrar</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('unltwebs.edit',$unltweb->id) }}"><i class="fa fa-fw fa-edit"></i> Editar</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Borrar</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $unltwebs->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/unltweb/show.blade.php
@extends('layouts.admin_raiz')

@section('contenido_app')

@include('layouts.barraSuperiorAdmin')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Muestra info del Alummno</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('unltwebs.index') }}"> Volver</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Apellido:</strong>
                            {{ $unltweb->apellido }}
                        </div>
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $unltweb->nombre }}
                        </div>
                        <div class="form-group">
                            <strong>Correo:</strong>
                            {{ $unltweb->correo }}
                        </div>
                        <div class="form-group">
                            <strong>Entorno:</strong>
                            {{ $unltweb->entorno }}
                        </div>
                        <div class="form-group">
                            <strong>Orientacion:</strong>
                            {{ $unltweb->orientacion }}
                        </div>
                        <div class="form-group">
                            <strong>Conocimientos:</strong>
                            {{ $unltweb->conocimientos }}
                        </div>
                        <div class="form-group">
                            <strong>Tp1 Html:</strong>
                            {{ $unltweb->tp1_html }}
                        </div>
                        <div class="form-group">
                            <strong>Tp2 Css:</strong>
                            {{ $unltweb->tp2_css }}
                        </div>
                        <div class="form-group">
                            <strong>Tp3 Servidores:</strong>
                            {{ $unltweb->tp3_servidores }}
                        </div>
                        <div class="form-group">
                            <strong>Tp4 Http:</strong>
                            {{ $unltweb->tp4_http }}
                        </div>
                        <div class="form-group">
                            <strong>Encuentro:</strong>
                            {{ $unltweb->encuentro }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection